---
# tasks file for timesyncd
- name: Ensure timesyncd is installed on {{ hostname }}
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: latest
  register: timesyncd_result

- name: Ensure scripts directory is present on {{ hostname }}
  ansible.builtin.file:
    path: "{{ remote_script_path }}"
    owner: root
    group: root
    mode: '0755'
    recurse: True
    state: directory

- name: Copying configuration template for timesyncd on {{ hostname }}
  ansible.builtin.template:
    src: "{{ local_conf_path }}/{{ timesyncd_conf }}"
    dest: "{{ remote_conf_path }}/{{ timesyncd_conf }}"
    owner: root
    group: root
    mode: '0644'
    force: True
  register: timesyncd_conf_output
  notify:
    - Restart timesyncd on conf file changes

- name: Configure timezone on {{ hostname }}
  ansible.builtin.command: 'timedatectl set-timezone "Asia/Taipei"'
  register: timezone_output

- name: Configure ntp settings on {{ hostname }}
  ansible.builtin.command: 'timedatectl set-ntp true'
  register: ntp_settings_output

- name: Starting timesyncd service on {{ hostname }}
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: True
