---
# tasks file for display
- name: Create a display directory builtin-scripts on {{ hostname }}
  ansible.builtin.file:
    path: "{{ remote_display_path }}"
    owner: root
    group: root
    mode: '0755'
    recurse: True
    state: directory

- name: Ensure that git is installed for display scripts on  {{ hostname }}
  ansible.builtin.apt:
    name: "{{ item }} "
    state: latest
    force_apt_get: true
  with_items:
    - git
  register: display_git_result


- name: Download display scripts from github to {{ hostname }}
  ansible.builtin.git:
    repo: "{{ display_git_repo }}"
    dest: "{{ remote_display_path }}"
    single_branch: true
    version: master
    force: true

- name: Validate display scripts on {{ hostname }}
  ansible.builtin.command:
    cmd: ls "{{ remote_display_path }}"
  register: display_result
- debug:
    msg: "{{ display_result.stdout_lines }}"