---
# Install utility packages
- hosts: creampi
  gather_facts: false
  tags: 'util_pkgs'
  become: true
  tasks: 
  - name: Install utility packages on {{ hostname }}
    ansible.builtin.apt: 
      name: "{{ item }}" 
      state: latest
      force_apt_get: true
    with_items:
      - zip
      - duf
      - htop 
      - file
      - dkms
      - tmux
      - lshw
      - unzip
      - unrar
      - chafa
      - lolcat
      - bsdutils
      - usbutils
      - chromium
      - p7zip-full
      - firefox-esr
      - libraspberrypi-bin
    register: apt_result