---
# tasks file for resolved
- name: Ensure resolved is installed on {{ hostname }}
  ansible.builtin.apt:
    name: systemd-resolved
    state: latest
  register: resolved_service

- name: Copying configuration template for resolved on {{ hostname }}
  ansible.builtin.template:
    src: "{{ local_conf_path }}/{{ resolved_conf }}"
    dest: "{{ remote_conf_path }}/{{ resolved_conf }}"
    owner: root
    group: root
    mode: '0644'
    force: true
  notify:
    - Restart resolved on conf file changes

- name: Starting resolved service on {{ hostname }}
  ansible.builtin.service:
    name: systemd-resolved
    state: started
    enabled: true