---
# tasks file for sshd
- name: Ensure sshd is installed on {{ hostname }}
  ansible.builtin.apt:
    name: ssh
    state: latest
  register: ssh_is_installed

- name: Copying configuration template for sshd on {{ hostname }}
  ansible.builtin.template:
    src: "{{ local_conf_path }}/{{ ssh_conf }}"
    dest: "{{ remote_conf_path }}/{{ ssh_conf }}"
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    force: true
  notify:
    - Restart sshd conf file changes

- name: Starting ssh service on {{ hostname }}
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true
