- name: Ensure iptables is installed on {{ hostname }}
  ansible.builtin.apt:
    name: iptables
    state: latest
  register: iptables_install

- name: Ensure iptables-persistent is installed on {{ hostname }}
  ansible.builtin.apt:
    name: iptables-persistent
    state: latest
  register: iptables_persistent_install

- name: Copying iptables script 
  ansible.builtin.copy:
    remote_src: False
    src: "{{ local_script_path }}/{{ iptables_script }}"
    dest: "{{ remote_script_path }}/{{ iptables_script }}"
    owner: root
    group: root
    mode: '0700'
    force: True

- name: Copying iptables persistence service
  ansible.builtin.copy:
    remote_src: False
    src: "{{ local_service_path }}/{{ iptables_service }}"
    dest: "{{ remote_service_path }}/{{ iptables_service }}"
    owner: root
    group: root
    mode: '0644'
    force: True

- name: Copying stateful firewall rules
  ansible.builtin.copy:
    remote_src: False
    src: "{{ local_conf_path }}/{{ iptables_rules }}"
    dest: "{{ remote_conf_path }}/{{ iptables_rules }}"
    owner: root
    group: root
    mode: '0644'
    force: True

- name: Validating iptables-netfilter service
  ansible.builtin.service:
    name: "{{ iptables_service }}"
    state: stopped
    enabled: True