#!/bin/bash
#
# disable_dhcpd.sh - Disables the dhcp server of the system.
#
# NOTE:
# dhcpd service - will not work if the droppi acts as a client and connected to wireless AP
#
# It may rely on hostapd service, to provide ip address on connecting hosts.
# Also, if the system is connected to a wireless AP, it acts as a client, therefore
# isc-dhcp-server.service may fail to run.

check_root() {
  if [ "$(id -u)" != "0" ]; then
    echo "ERROR: $0 must be run as root"
    exit 1
  fi
}

disable_dhcpd() {
  echo -e "Disabling isc-dhcp-server service..\n"
  systemctl disable --now isc-dhcp-server.service
  systemctl status isc-dhcp-server.service --no-pager
}

main() {
  check_root
  disable_dhcpd
}

main
