#!/bin/bash
#
# disable_hostapd.sh - Disables the hostapd of the system.
#
# NOTE:
# hostapd service - will not work if the droppi acts as a client and connected to wireless AP
#
# It may rely on how the system acts on the network to provide wireless ap service.
# Also, if the system is connected to a wireless AP, it acts as a client, therefore
# hostapd may fail on providing ssid as an access point.

check_root() {
  if [ "$(id -u)" != "0" ]; then
    echo "ERROR: $0 must be run as root"
    exit 1
  fi
}

disable_hostapd() {
  echo -e "Disabling hostapd service..\n"
  systemctl disable --now hostapd.service
  systemctl status hostapd.service --no-pager
}

main() {
  check_root
  disable_hostapd
}

main
