#!/bin/bash
#
# enable_sshtunnel.sh - Enable sshtunnel service
#
# sshtunnel.service executes a reverse ssh tunnel on a remote server specified
#
# Note that the sshtunnel.service must be installed on the system prior running the script.
#

check_root() {
  if [ "$(id -u)" != "0" ]; then
    echo "ERROR: $0 must be run as root"
    exit 1
  fi
}

enable_sshtunnel() {
  if [ ! -f /opt/scripts/startup/sshtunnel.sh ] && [ ! -f /etc/systemd/system/sshtunnel.service ]
    then
      echo "ERROR: sshtunnel.service is not installed on ${HOSTNAME}."
      exit 1
  else
    echo -e "Enabling sshtunnel.service.."
    systemctl enable --now sshtunnel.service
    systemctl status sshtunnel.service --no-pager
  fi
}

main() {
  check_root
  enable_sshtunnel
}

main
