#!/bin/bash
#
# Checks the hardware info of the pi
#

check_root() {
  if [ "$(id -u)" != "0" ]; then 
    echo " must() be run as root"
    exit 1
  fi
}

check_cpuinfo() {
  echo -e "------------------- CPUINFO -------------------"
  lscpu | grep 'Architecture' -A20 
}

main() {
    check_root
    check_cpuinfo
}

main
