#!/bin/bash
#
# Checks the current storage of rasberry pi
#

check_root() {
  if [ "$(id -u)" != "0" ]; then 
    echo "ERROR: $0 must be run as root"
    exit 1
  fi
}

check_storage() {
  df -h
  echo
  df -h | grep /root -B1
  echo
  duf
}

main() {
    check_root
    check_storage
}

main
