---
# Load data from config.json
- import_playbook: ../vars/data.yml

### Configure built-in scripts
- hosts: creampi
  gather_facts: false
  tags: 'builtin_scripts'
  become: true
  vars:
    remote_hardware_path: "{{ system.scripts.hardware.remotePath }}"
    local_hardware_path: "{{ system.scripts.hardware.localPath }}"
    remote_network_path: "{{ system.scripts.network.remotePath }}"
    local_network_path: "{{ system.scripts.network.localPath }}"
    display_git_repo: "{{ system.scripts.display.gitRepo }}"
    remote_display_path: "{{ system.scripts.display.remotePath }}"
    display_lib_path: "{{ system.scripts.display.LibPath}}"
    local_display_path: "{{ system.scripts.display.localPath }}"
    lcd_35: "{{ system.scripts.display.lcd35 }}"
    lcd_5: "{{ system.scripts.display.lcd5 }}"
    lcd_7b: "{{ system.scripts.display.lcd7b }}"
    lcd_7c: "{{ system.scripts.display.lcd7c }}"
    lcd_7h: "{{ system.scripts.display.lcd7h }}"
    lcd_hdmi: "{{ system.scripts.display.lcdHdmi }}" 

  tasks:
  - name: Create a display directory builtin-scripts to {{ hostname }}
    ansible.builtin.file:
      path: "{{ remote_display_path }}"
      owner: root
      group: root
      mode: '0755'
      recurse: yes
      state: directory

  - name: Create a hardware directory builtin-scripts to {{ hostname }}
    ansible.builtin.file:
      path: "{{ remote_hardware_path }}"
      owner: root
      group: root
      mode: '0755'
      recurse: yes
      state: directory

  - name: Create a network directory builtin-scripts to {{ hostname }}
    ansible.builtin.file:
      path: "{{ remote_network_path }}"
      owner: root
      group: root
      mode: '0755'
      recurse: yes
      state: directory

  - name: Copy all raspberry pi hardware scripts to {{ hostname }}
    ansible.builtin.copy:
      remote_src: false
      src: "{{ local_hardware_path }}/"
      dest: "{{ remote_hardware_path }}/"
      owner: root
      group: root
      mode: '0755'
      force: false

  - name: Copy all raspberry pi network scripts to {{ hostname }}
    ansible.builtin.copy:
      remote_src: false
      src: "{{ local_network_path }}/"
      dest: "{{ remote_network_path }}/"
      owner: root
      group: root
      mode: '0755'
      force: false

  - name: Download raspbery pi display scripts to {{ hostname }}
    ansible.builtin.git:
      repo: "{{ display_git_repo }}"
      dest: "{{ display_lib_path }}/"
      single_branch: true
      version: master
      force: true
    ignore_errors: true
    no_log: true

  - name: Create display symlink to display scripts directory to {{ hostname }}
    ansible.builtin.file:
      src: "{{ display_lib_path }}/{{ item.src }}"
      dest: "{{ remote_display_path }}/{{ item.dest }}"
      owner: root
      group: root
      state: link
      force: true
    loop:
      - { src: "{{ lcd_35 }}", dest: "{{ lcd_35 }}" }
      - { src: "{{ lcd_5 }}", dest: "{{ lcd_5 }}" }
      - { src: "{{ lcd_7b }}", dest: "{{ lcd_7b }}" }
      - { src: "{{ lcd_7c }}", dest: "{{ lcd_7c }}" }
      - { src: "{{ lcd_7h }}", dest: "{{ lcd_7h }}" }
      - { src: "{{ lcd_hdmi }}", dest: "{{ lcd_hdmi }}" }