---
# Load data from config.json
- import_playbook: ../vars/data.yml

### Update hosts configuration
- hosts: creampi
  gather_facts: false
  tags: 'host_config'
  become: true
  vars:
    default_hostname: "{{ system.config.hosts.default }}"
    hosts_file: "{{ system.config.hosts.file }}"
    motd_file: "{{ system.config.motd.file }}"
    motd_path: "{{ system.config.motd.path }}"
    issue_file: "{{ system.config.issue.file }}"
    issue_path: "{{ system.config.issue.path }}"
    
  tasks:
  - name: Update password for {{ ansible_user }} user on {{ hostname }}
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      state: present
      password: "{{ user_password | password_hash('sha512') }}"

  - name: Update password for root user on {{ hostname }}
    ansible.builtin.user:
      name: 'root'
      state: present
      password: "{{ root_password | password_hash('sha512') }}"

  - name: Update new hostname on {{ hostname }}
    ansible.builtin.hostname:
      name: "{{ hostname }}"

  - name: Update new hostname in /etc/hosts on {{ hostname }}
    ansible.builtin.replace:
      path: "{{ hosts_file }}"
      regexp: "{{ default_hostname }}"
      replace: "{{ hostname }}"

  - name: Create a backup for motd banner on {{ hostname }}
    ansible.builtin.copy:
      remote_src: true
      src: "{{ motd_path }}"
      dest: "{{ motd_path }}.bak"
      force: false

  - name: Configure new motd banner on {{ hostname }}
    ansible.builtin.copy:
      remote_src: false
      src: "{{ motd_file }}"
      dest: "{{ motd_path }}"
      force: true

  - name: Create a backup for login banner on {{ hostname }}
    ansible.builtin.copy:
      remote_src: true
      src: "{{ issue_path }}"
      dest: "{{ issue_path }}.bak"
      force: false

  - name: Configure new login banner on {{ hostname }}
    ansible.builtin.copy:
      remote_src: false
      src: "{{ issue_file }}"
      dest: "{{ issue_path }}"
      force: true