---
# Load data from config.json
- import_playbook: ../vars/data.yml

### Update other miscellaneous configs
- hosts: creampi
  gather_facts: false
  tags: 'misc_config'
  become: true
  vars:
    network_manager_path: "{{ system.misc.networkManager.path }}"
    network_manager_file: "{{ system.misc.networkManager.file }}"
    network_manager_template: "{{ system.misc.networkManager.template }}"

  tasks:
  - name: Disable auto sleep and hibernate on {{ hostname }}
    ansible.builtin.command: 'systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target'
    register: auto_sleep_output

  - name: Update system mlocate database on {{ hostname }}
    ansible.builtin.command: updatedb
    register: updatedb_output

  - name: Create a backup for NetworkManager.conf on {{ hostname }}
    ansible.builtin.copy:
      remote_src: true
      src: "{{ network_manager_path }}/{{ network_manager_file }}"
      dest: "{{ network_manager_path }}/{{ network_manager_file }}.bak"
      force: false

  - name: Ensure to remove old NetworkManager config on {{ hostname }}
    ansible.builtin.shell: 
      cmd: 'nmcli con del "Ifupdown (eth0)"'
      removes: '{{ network_manager_path }}/system-connections/"Ifupdown (eth0).nmconnection"'

  - name: Configure managed interface for NetworkManager on {{ hostname }}
    ansible.builtin.copy:
      remote_src: false
      src: "{{ network_manager_template }}/{{ network_manager_file }}"
      dest: "{{ network_manager_path }}/{{ network_manager_file }}"
      force: true
      