---
- name: "Read data files"
  hosts: all
  vars_files:
    - "config.json"

  tasks:
    - name: save the Json data to a Variable as a Fact
      set_fact:
        services: "{{ services }}"
        cacheable: yes