---
# Load data from config.json
- import_playbook: ../vars/data.yml

# Configure resolved daemon
- hosts: creampi
  gather_facts: no
  tags: 'resolved_service'
  become: true
  vars:
    remote_conf_path: "{{ services.resolved.conf.remotePath }}"
    local_conf_path: "{{ services.resolved.conf.localPath }}"
    resolved_conf: "{{ services.resolved.conf.template }}"

  tasks:
  - name: Ensure resolved is installed on {{ hostname }}
    ansible.builtin.apt:
      name: systemd-resolved
      state: latest
    register: resolved_service

  - name: Copying configuration template for resolved on {{ hostname }}
    ansible.builtin.template:
      src: "{{ local_conf_path }}/{{ resolved_conf }}"
      dest: "{{ remote_conf_path }}/{{ resolved_conf }}"
      owner: root
      group: root
      mode: '0644'
      force: true
    notify:
      - Restart resolved on conf file changes

  - name: Starting resolved service on {{ hostname }}
    ansible.builtin.service:
      name: systemd-resolved
      state: started
      enabled: true

  handlers:
    - name: Restart resolved on conf file changes
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted