---
# Load data from config.json
- import_playbook: ../vars/data.yml

# Configure timesyncd daemon
- hosts: creampi
  gather_facts: no
  tags: 'timesyncd_service'
  become: true
  vars:
    remote_conf_path: "{{ services.timesyncd.conf.remotePath }}"
    local_conf_path: "{{ services.timesyncd.conf.localPath }}"
    timesyncd_conf: "{{ services.timesyncd.conf.template }}"

  tasks:
  - name: Ensure timesyncd is installed on {{ hostname }}
    ansible.builtin.apt:
      name: systemd-timesyncd
      state: latest
    register: timesyncd_result

  - name: Copying configuration template for timesyncd on {{ hostname }}
    ansible.builtin.template:
      src: "{{ local_conf_path }}/{{ timesyncd_conf }}"
      dest: "{{ remote_conf_path }}/{{ timesyncd_conf }}"
      owner: root
      group: root
      mode: '0644'
      force: true
    register: timesyncd_conf_output
    notify:
      - Restart timesyncd on conf file changes

  - name: Configure timezone on {{ hostname }}
    ansible.builtin.command: 'timedatectl set-timezone "Asia/Taipei"'
    register: timezone_output

  - name: Configure ntp settings on {{ hostname }}
    ansible.builtin.command: 'timedatectl set-ntp true'
    register: ntp_settings_output

  - name: Starting timesyncd service on {{ hostname }}
    ansible.builtin.service:
      name: systemd-timesyncd
      state: started
      enabled: true

  handlers:
    - name: Restart timesyncd on conf file changes
      ansible.builtin.service:
        name: systemd-timesyncd
        state: restarted