---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

- name: Installing aquatone
  hosts: creampi
  gather_facts: False
  become: True
  tags: 'aquatone_imager'
  
  roles:
  - { role: 'tools/scanner/aquatone', tags: 'aquatone_imager'}
  vars:
    exe_path: "{{ creampi.tools.scanner.path.executable }}"
    scanner_path: "{{ creampi.tools.scanner.path.scanner }}"
    aquatone_release: "{{ creampi.tools.scanner.releases.aquatone }}"