---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

- name: Installing bloodhound-ce ingestor from github
  hosts: creampi
  gather_facts: False
  become: True
  tags: 'bloodhound_ce_git'

  roles:
  - { role: 'tools/network/bloodhound-ce-ingestor', tags: 'bloodhound_ce_git'}
  vars:
    net_module_path: "{{ creampi.tools.network.path.module }}"
    bloodhound_git: "{{ creampi.tools.network.git.bloodhound }}"
