---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

- name: Installing gowitness
  hosts: creampi
  gather_facts: False
  become: True
  tags: 'gowitness_imager'
  
  roles:
  - { role: 'tools/scanner/gowitness', tags: 'gowitness_imager'}
  vars:
    exe_path: "{{ creampi.tools.scanner.path.executable }}"
    scanner_path: "{{ creampi.tools.scanner.path.scanner }}"
    gowitness_release: "{{ creampi.tools.scanner.releases.gowitness }}"