---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

- name: Installing katana
  hosts: creampi
  gather_facts: False
  become: True
  tags: 'katana_crawler'
  
  roles:
  - { role: 'tools/scanner/katana', tags: 'katana_crawler'}
  vars:
    exe_path: "{{ creampi.tools.scanner.path.executable }}"
    scanner_path: "{{ creampi.tools.scanner.path.scanner }}"
    katana_release: "{{ creampi.tools.scanner.releases.katana }}"