---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

- name: Installing legacy responder
  hosts: creampi
  gather_facts: False
  become: True
  tags: 'legacy_responder'
  
  roles:
  - { role: 'tools/network/legacy-responder', tags: 'legacy_responder'}