---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

- name: Installing metasploit framework
  hosts: creampi
  gather_facts: False
  become: True
  tags: 'metasploit_framework'

  roles:
  - { role: 'tools/network/metasploit', tags: 'metasploit_framework'}
