---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

- name: Installing nuclei
  hosts: creampi
  gather_facts: False
  become: True
  tags: 'nuclei_scanner'
  
  roles:
  - { role: 'tools/scanner/nuclei', tags: 'nuclei_scanner'}
  vars:
    exe_path: "{{ creampi.tools.scanner.path.executable }}"
    scanner_path: "{{ creampi.tools.scanner.path.scanner }}"
    nuclei_release: "{{ creampi.tools.scanner.releases.nuclei }}"