
---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

- name: Rebooting devices
  hosts: creampi
  gather_facts: False
  become: True
  tags: 'reboot_result'

  tasks:
  - name: Check if 'make' process is still running
    ansible.builtin.shell: |
      ps aux | grep "[m]ake"
    register: make_process
    retries: 10       
    delay: 20        
    until: make_process.stdout == ""
    failed_when: false

  - name: Continue with reboot after 'make' finishes
    ansible.builtin.shell:
      cmd: echo "Proceeding with the next task."
      
  - name: Rebooting {{ hostname }} for provisioning changes
    ansible.builtin.shell:
      cmd: echo "Ansible {{ hostname }} provisioning changes. Rebooting after 10s"
    register: reboot_msg
  - debug:
      msg: '{{ reboot_msg.stdout_lines }}'

  - name: Rebooting the {{ hostname }} in 10 seconds
    ansible.builtin.shell:
      cmd: |
        echo "Ansible {{ hostname }} provisioning changes Rebooting after 10s 2>&1 \
        | wall && sleep 9"

  - name: Rebooting {{ hostname }} (Task will fail due to connectivity)
    ansible.builtin.reboot:
      reboot_timeout: 10