
---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

- name: Rebooting devices
  hosts: creampi
  gather_facts: False
  become: True
  tags: 'reboot_result'

  tasks:
  - name: Rebooting {{ hostname }} for provisioning changes
    ansible.builtin.shell:
      cmd: echo "Ansible {{ hostname }} provisioning changes. Rebooting after 10s"
    register: reboot_msg
  - debug:
      msg: '{{ reboot_msg.stdout_lines }}'

  - name: Rebooting the {{ hostname }} in 10 seconds
    ansible.builtin.shell:
      cmd: |
        echo "Ansible {{ hostname }} provisioning changes Rebooting after 10s 2>&1 \
        | wall && sleep 9"

  - name: Rebooting {{ hostname }} (Task will fail due to connectivity)
    ansible.builtin.reboot:
      reboot_timeout: 10