---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

- name: Installing rusthound ingestor
  hosts: creampi
  gather_facts: False
  become: True
  tags: 'rusthound_ingest'
  
  roles:
  - { role: 'tools/network/rusthound', tags: 'rusthound_ingest'}
  vars:
    net_module_path: "{{ creampi.tools.network.path.module }}"
    rusthound_git: "{{ creampi.tools.network.git.rusthound }}"