---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

- name: Install utility packages
  hosts: creampi
  gather_facts: False
  become: True
  tags: 'util_pkgs'
  
  roles:
  - { role: 'packages/util', tags: 'util_pkgs'}