---
# Load data from config.json
- import_playbook: ../vars/data.yml

- hosts: creampi
  gather_facts: false
  tags: 'physical_modules'
  become: true
  vars:
    phy_module_path: "{{ tools.physical.path.module }}"
    nac_bypass_git: "{{ tools.physical.git.nacBypass }}"
    silentbridge_git: "{{ tools.physical.git.silentBridge }}"
  
  tasks:
  - name: Create a directory for physical bypass tools on {{ hostname }}
    ansible.builtin.file:
      path: "{{ phy_module_path }}"
      owner: root
      group: root
      mode: '0755'
      state: directory

  - name: Download nac bypass module tool if not installed on {{ hostname }}
    ansible.builtin.shell:
      cmd: 'git clone {{ nac_bypass_git }} {{ phy_module_path }}/nac_bypass'
      creates: "{{ phy_module_path }}/nac_bypass"

  - name: Download silentbridge module tool if not installed on {{ hostname }}
    ansible.builtin.shell:
      cmd: 'git clone {{ silentbridge_git }} {{ phy_module_path }}/silentbridge'
      creates: "{{ phy_module_path }}/silentbridge"