---

##
# 
# Basic installation playbook:
#   - No stateful firewall installed
#   - Few network tools installed
#   - Basic Tunneling protocols SSH / VPN
#   - Fast Installation time
#
##

# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../data/"
  tags: 'data'

## System configuration ------
- import_playbook: apt.yml
- import_playbook: scripts.yml
- import_playbook: host.yml
- import_playbook: misc.yml
## Packages ------
# Consists of required packages
# to operate in a minimalistic manner
# using common tools and dependencies needed
- import_playbook: lib.yml
- import_playbook: devel.yml
- import_playbook: net.yml
- import_playbook: util.yml
# devel tools
- import_playbook: go.yml
- import_playbook: pip2.yml
## Service installation ------
# Security configuration and other utilities
# needed to function the pi server
- import_playbook: resolved.yml
- import_playbook: sshd.yml
- import_playbook: timesyncd.yml
- import_playbook: sshtun.yml
- import_playbook: vpntun.yml
## PT Tools ------
# Internal pt tools that can be used
# to enumerate, exploit target systems
# without the need of proxy
#
# network tools
- import_playbook: igandx-responder.yml
- import_playbook: legacy-responder.yml
# scanner tools
- import_playbook: aquatone.yml
- import_playbook: httpx.yml
- import_playbook: nuclei.yml
- import_playbook: nuclei-templates.yml

## Change default credentials of creampi hosts
- import_playbook: user.yml
## Finally, reboot to validate changes
- import_playbook: reboot.yml