---
# tasks file for sliver
- name: Download sliver c2 server on {{ hostname }}
  ansible.builtin.git:
    repo: "{{ sliver_git_repo }}"
    dest: "{{ net_module_path }}/sliver"
    single_branch: true
    version: master
    force: true

- name: Build sliver c2 server on {{ hostname }}
  ansible.builtin.shell:
    cmd: |
      cd {{ net_module_path }}/sliver && \
      export GOOS=linux; \
      export GOARCH=arm64; \
      nohup make > /dev/null 2>&1 &
    creates: "{{ net_module_path }}/sliver/sliver-server"

# - name: Set path for sliver c2 on {{ hostname }}
#   ansible.builtin.shell:
#     cmd: |
#       ln -s {{ net_module_path }}/sliver/sliver-server {{ sliver_exec_path }}/sliver-server && 2>/dev/null \
#       ln -s {{ net_module_path }}/sliver/sliver-client {{ sliver_exec_path }}/sliver-client 2>/dev/null
#     creates: "{{ sliver_exec_path }}/sliver/sliver-server"

- name: Create netexec symlinks in executable path on {{ hostname }}
  ansible.builtin.file:
    src: "{{ net_module_path }}/sliver/{{ item.src }}"
    dest: "{{ sliver_exec_path }}/{{ item.dest }}"
    state: link
    force: True
  loop:
    - { src: sliver-server, dest: sliver-server }
    - { src: sliver-client, dest: sliver-client }