---
# tasks file for knockd
- name: Ensure knockd is installed on {{ hostname }}
  ansible.builtin.apt:
    name: knockd
    state: latest
  register: knockd_install

- name: Copying knockd script on {{ hostname }}
  ansible.builtin.copy:
    remote_src: false
    src: "{{ local_script_path }}/{{ knockd_script }}"
    dest: "{{ remote_script_path }}/{{ knockd_script }}"
    owner: root
    group: root
    mode: '0700'
    force: true

- name: Copying knockd configuration file on {{ hostname }}
  ansible.builtin.template:
    src: "{{ local_conf_path }}/{{ knockd_conf }}"
    dest: "{{ remote_conf_path }}/{{ knockd_conf }}"
    owner: root
    group: root
    mode: '0644'
    force: true
  register: knockd_conf
  notify:
    - Restart knockd on conf file changes

- name: Copy knockd checker custom service on {{ hostname }}
  ansible.builtin.copy:
    remote_src: false
    src: "{{ local_service_path }}/{{ knockd_iface_checker }}"
    dest: "{{ remote_service_path }}/{{ knockd_iface_checker }}"
    owner: root
    group: root
    mode: '0644'
    force: true
  register: knockd_checker_service

- name: Ensure to reload systemd daemon for changes on {{ hostname }}
  ansible.builtin.shell:
    cmd: 'systemctl daemon-reload'
  when: knockd_checker_service.changed

- name: Starting knockd service on {{ hostname }}
  ansible.builtin.service:
    name: "{{ knockd_service }}"
    state: started
    enabled: true

- name: Starting knockd checker service on {{ hostname }}
  ansible.builtin.service:
    name: "{{ knockd_iface_checker }}"
    state: started
    enabled: true