#!/bin/bash
#
# disconnect_wlan_nmcli.sh - disconnect CREAMpi to a wireless network
# 
# WARNING:
#   if you are not connected to the ETH interface on the local network,
#   and you manage CREAMpi from ssh over wireless, you will get disconnected.
#
#   If persist on boot is set to 1, CREAMpi will forget the network and will not
#   connect on boot.
#
# Set the following variables before running the script.

SSID_NAME=''
PERSIST_ON_BOOT=0
WLAN_INTERFACE=wlan0

check_root() {
  if [ "$(id -u)" != "0" ]; then 
    echo "ERROR: $0 must be run as root"
    exit 1
  fi
}

check_wlan_interfaces() {
  WLAN_INTERFACES=()
  WLAN_INTERFACES+=$(ip route list | grep -v default | awk '{print $3}' | grep w | sort -u)

  if [[ ! ${WLAN_INTERFACES[*]} =~ ${WLAN_INTERFACE} ]]; then
    echo "ERROR: WLAN_INTERFACE error. Check configuration file for $0"
    exit 1
  else
    if [[ -z ${SSID_NAME} ]]; then
      echo "ERROR: Supply a valid SSID_NAME"
      exit
    fi
    
    echo "Disconnecting to target wifi with SSID: ${SSID_NAME}"..
    sleep 1.5
  fi

}

disconnect_wlan() {
  nmcli con show
  nmcli con down id "${SSID_NAME}"
  if [ ${PERSIST_ON_BOOT} == 1 ]; then
    nmcli con down id "${SSID_NAME}"
    nmcli con delete id "${SSID_NAME}"
  elif [ $PERSIST_ON_BOOT == 0 ]; then
    nmcli con down id "${SSID_NAME}"
  else
    echo "Error on ther configuration file.. exiting.."
    exit 1
  fi
  ifconfig ${WLAN_INTERFACE}

}

main() {
  check_root
  check_wlan_interfaces
  disconnect_wlan
}

main
