#!/bin/bash
#
# enable_hostapd.sh - Enables the hostapd of the system.
#
# NOTE:
# hostapd service - will not work if the droppi acts as a client and connected to wireless AP
#
# It may rely on how the system acts on the network to provide wireless ap service.
# Also, if the system is connected to a wireless AP, it acts as a client, therefore
# hostapd may fail on providing ssid as an access point.

check_root() {
  if [ "$(id -u)" != "0" ]; then
    echo "ERROR: $0 must be run as root"
    exit 1
  fi
}

enable_hostapd() {
  echo -e "Enabling hostapd service..\n"
  systemctl enable --now hostapd.service
  systemctl status hostapd.service --no-pager
}

main() {
  check_root
  enable_hostapd
}

main
